version: "3"
services:
  redis:
    image: redis:alpine
  app:
    build: "."
    ports: ["8081:8081"]
    links: [redis]
    environment:
      - FLY_REDIS_CACHE_URL=redis://redis
      - HTTP_USER
      - HTTP_PASSWORD
