openapi: 3.0.3
info:
  title: ts-openapi
  version: 1.0.0
servers:
  - url: http://localhost:3000/api
paths:
  /hello:
    get:
      responses:
        "200":
          description: "OK"
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/hello"
components:
  schemas:
    hello:
      type: string
      pattern: ^hello$
