name: docs
on: push
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with: { node-version: 12 }
      - run: yarn
      - run: NEXT_ASSET_PREFIX=/${GITHUB_REPOSITORY#*/} yarn doc
      - run: git add docs
      - run: git -c user.name=octocat -c user.email=octocat@github.com commit -m docs
      - run: git remote set-url github "https://${NAME}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
        env:
          NAME: octocat
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: git push github "${GITHUB_REF}"
